/*
 * Created on 29 déc. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.immo.bean.Dossier;
import com.immo.bean.jpa.DossierEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DossierServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DossierServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DossierEntity' to 'Dossier'
	 * @param dossierEntity
	 */
	public Dossier mapDossierEntityToDossier(DossierEntity dossierEntity) {
		if(dossierEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Dossier dossier = map(dossierEntity, Dossier.class);

		return dossier;
	}
	
	/**
	 * Mapping from 'Dossier' to 'DossierEntity'
	 * @param dossier
	 * @param dossierEntity
	 */
	public void mapDossierToDossierEntity(Dossier dossier, DossierEntity dossierEntity) {
		if(dossier == null) {
			return;
		}

		//--- Generic mapping 
		map(dossier, dossierEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}