/*
 * Created on 29 déc. 2015 ( Time 20:53:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.immo.bean.ReferenceType;
import com.immo.bean.jpa.ReferenceTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ReferenceTypeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ReferenceTypeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ReferenceTypeEntity' to 'ReferenceType'
	 * @param referenceTypeEntity
	 */
	public ReferenceType mapReferenceTypeEntityToReferenceType(ReferenceTypeEntity referenceTypeEntity) {
		if(referenceTypeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ReferenceType referenceType = map(referenceTypeEntity, ReferenceType.class);

		return referenceType;
	}
	
	/**
	 * Mapping from 'ReferenceType' to 'ReferenceTypeEntity'
	 * @param referenceType
	 * @param referenceTypeEntity
	 */
	public void mapReferenceTypeToReferenceTypeEntity(ReferenceType referenceType, ReferenceTypeEntity referenceTypeEntity) {
		if(referenceType == null) {
			return;
		}

		//--- Generic mapping 
		map(referenceType, referenceTypeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}