/*
 * Created on 29 d�c. 2015 ( Time 20:53:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Bien;
import com.immo.bean.Projet;
import com.immo.bean.Tranche;

/**
 * Business Service Interface for entity Bien.
 */
public interface BienService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Bien findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Bien> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Bien save(Bien entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Bien update(Bien entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Bien create(Bien entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	List<Bien> findBienByProjet(Projet p);

	List<Bien> findBienByTranche(Tranche t);

	List<Object> etatBien();


}
