/*
 * Created on 29 d�c. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Client;

/**
 * Business Service Interface for entity Client.
 */
public interface ClientService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Client findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Client> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Client save(Client entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Client update(Client entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Client create(Client entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	Client clientByCin(String cin, Long quote);


}
