/*
 * Created on 29 d�c. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Client;
import com.immo.bean.Dossier;
import com.immo.bean.DossierClient;

/**
 * Business Service Interface for entity DossierClient.
 */
public interface DossierClientService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DossierClient findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DossierClient> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DossierClient save(DossierClient entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DossierClient update(DossierClient entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DossierClient create(DossierClient entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	List<DossierClient> findByDossier(Long id);

	List<Client> findClientByDossier(Dossier p);


}
