/*
 * Created on 29 d�c. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Bienetclients;
import com.immo.bean.Dossier;
import com.immo.bean.InfoDossier;

/**
 * Business Service Interface for entity Dossier.
 */
public interface DossierService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Dossier findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Dossier> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Dossier save(Dossier entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Dossier update(Dossier entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Dossier create(Dossier entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	

	Dossier createdossier(Bienetclients requestWrapper);


	List<InfoDossier> findDossier(Long id);

	void annuleDossier(Dossier entity);

	List<Object> venteJournee();

}
