/*
 * Created on 29 d�c. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Dossier;
import com.immo.bean.Echeance;

/**
 * Business Service Interface for entity Echeance.
 */
public interface EcheanceService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Echeance findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Echeance> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Echeance save(Echeance entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Echeance update(Echeance entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Echeance create(Echeance entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	

	List<Echeance> findByDossier(Long id);

	List<Echeance> findEcheanceByDossier(Dossier d);


}
