/*
 * Created on 29 d�c. 2015 ( Time 20:53:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Dossier;
import com.immo.bean.Recette;
import com.immo.bean.jpa.DossierEntity;

/**
 * Business Service Interface for entity Recette.
 */
public interface RecetteService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Recette findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Recette> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Recette save(Recette entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Recette update(Recette entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Recette create(Recette entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	List<Recette> findByDossier(Dossier d);

	List<Recette> findByNumAndBanque(Recette recette);
	
	public Recette annulePaiement(Recette recette);

}
