/*
 * Created on 29 d�c. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.TraceDossier;

/**
 * Business Service Interface for entity TraceDossier.
 */
public interface TraceDossierService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TraceDossier findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TraceDossier> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TraceDossier save(TraceDossier entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TraceDossier update(TraceDossier entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TraceDossier create(TraceDossier entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
