/*
 * Created on 29 déc. 2015 ( Time 20:53:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Tranche;

/**
 * Business Service Interface for entity Tranche.
 */
public interface TrancheService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Tranche findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Tranche> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Tranche save(Tranche entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tranche update(Tranche entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tranche create(Tranche entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
