/*
 * Created on 29 d�c. 2015 ( Time 20:53:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service;

import java.util.List;

import com.immo.bean.Client;
import com.immo.bean.Dossier;
import com.immo.bean.Projet;
import com.immo.bean.Tranche;
import com.immo.bean.Utilisateur;
import com.immo.bean.UtilisateurTranche;

/**
 * Business Service Interface for entity UtilisateurTranche.
 */
public interface UtilisateurTrancheService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	UtilisateurTranche findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<UtilisateurTranche> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UtilisateurTranche save(UtilisateurTranche entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UtilisateurTranche update(UtilisateurTranche entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UtilisateurTranche create(UtilisateurTranche entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );

	List<Projet> findProjetByUser(Utilisateur u);
	
	List<Tranche> findTrancheByUser(Utilisateur u);


}
