/*
 * Created on 29 déc. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.immo.bean.Echeance;
import com.immo.bean.jpa.EcheanceEntity;
import com.immo.bean.jpa.DossierEntity;
import com.immo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class EcheanceServiceMapperTest {

	private EcheanceServiceMapper echeanceServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		echeanceServiceMapper = new EcheanceServiceMapper();
		echeanceServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'EcheanceEntity' to 'Echeance'
	 * @param echeanceEntity
	 */
	@Test
	public void testMapEcheanceEntityToEcheance() {
		// Given
		EcheanceEntity echeanceEntity = new EcheanceEntity();
		echeanceEntity.setNumero(mockValues.nextLong());
		echeanceEntity.setDateEcheance(mockValues.nextDate());
		echeanceEntity.setMontant(mockValues.nextLong());
		echeanceEntity.setObservation(mockValues.nextString(100));
		echeanceEntity.setPourcentage(mockValues.nextLong());
		echeanceEntity.setDateCreation(mockValues.nextDate());
		echeanceEntity.setDateMaj(mockValues.nextDate());
		echeanceEntity.setDossier(new DossierEntity());
		echeanceEntity.getDossier().setId(mockValues.nextLong());
		
		// When
		Echeance echeance = echeanceServiceMapper.mapEcheanceEntityToEcheance(echeanceEntity);
		
		// Then
		assertEquals(echeanceEntity.getNumero(), echeance.getNumero());
		assertEquals(echeanceEntity.getDateEcheance(), echeance.getDateEcheance());
		assertEquals(echeanceEntity.getMontant(), echeance.getMontant());
		assertEquals(echeanceEntity.getObservation(), echeance.getObservation());
		assertEquals(echeanceEntity.getPourcentage(), echeance.getPourcentage());
		assertEquals(echeanceEntity.getDateCreation(), echeance.getDateCreation());
		assertEquals(echeanceEntity.getDateMaj(), echeance.getDateMaj());
		assertEquals(echeanceEntity.getDossier().getId(), echeance.getRefDossier());
	}
	
	/**
	 * Test : Mapping from 'Echeance' to 'EcheanceEntity'
	 */
	@Test
	public void testMapEcheanceToEcheanceEntity() {
		// Given
		Echeance echeance = new Echeance();
		echeance.setNumero(mockValues.nextLong());
		echeance.setDateEcheance(mockValues.nextDate());
		echeance.setMontant(mockValues.nextLong());
		echeance.setObservation(mockValues.nextString(100));
		echeance.setPourcentage(mockValues.nextLong());
		echeance.setDateCreation(mockValues.nextDate());
		echeance.setDateMaj(mockValues.nextDate());
		echeance.setRefDossier(mockValues.nextLong());

		EcheanceEntity echeanceEntity = new EcheanceEntity();
		
		// When
		echeanceServiceMapper.mapEcheanceToEcheanceEntity(echeance, echeanceEntity);
		
		// Then
		assertEquals(echeance.getNumero(), echeanceEntity.getNumero());
		assertEquals(echeance.getDateEcheance(), echeanceEntity.getDateEcheance());
		assertEquals(echeance.getMontant(), echeanceEntity.getMontant());
		assertEquals(echeance.getObservation(), echeanceEntity.getObservation());
		assertEquals(echeance.getPourcentage(), echeanceEntity.getPourcentage());
		assertEquals(echeance.getDateCreation(), echeanceEntity.getDateCreation());
		assertEquals(echeance.getDateMaj(), echeanceEntity.getDateMaj());
		assertEquals(echeance.getRefDossier(), echeanceEntity.getDossier().getId());
	}

}