/*
 * Created on 29 déc. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.immo.bean.Module;
import com.immo.bean.jpa.ModuleEntity;
import com.immo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ModuleServiceMapperTest {

	private ModuleServiceMapper moduleServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		moduleServiceMapper = new ModuleServiceMapper();
		moduleServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ModuleEntity' to 'Module'
	 * @param moduleEntity
	 */
	@Test
	public void testMapModuleEntityToModule() {
		// Given
		ModuleEntity moduleEntity = new ModuleEntity();
		moduleEntity.setNiveau(mockValues.nextString(100));
		moduleEntity.setIdConponenet(mockValues.nextString(100));
		moduleEntity.setDomaine(mockValues.nextString(100));
		moduleEntity.setDateCreation(mockValues.nextDate());
		moduleEntity.setDateMaj(mockValues.nextDate());
		
		// When
		Module module = moduleServiceMapper.mapModuleEntityToModule(moduleEntity);
		
		// Then
		assertEquals(moduleEntity.getNiveau(), module.getNiveau());
		assertEquals(moduleEntity.getIdConponenet(), module.getIdConponenet());
		assertEquals(moduleEntity.getDomaine(), module.getDomaine());
		assertEquals(moduleEntity.getDateCreation(), module.getDateCreation());
		assertEquals(moduleEntity.getDateMaj(), module.getDateMaj());
	}
	
	/**
	 * Test : Mapping from 'Module' to 'ModuleEntity'
	 */
	@Test
	public void testMapModuleToModuleEntity() {
		// Given
		Module module = new Module();
		module.setNiveau(mockValues.nextString(100));
		module.setIdConponenet(mockValues.nextString(100));
		module.setDomaine(mockValues.nextString(100));
		module.setDateCreation(mockValues.nextDate());
		module.setDateMaj(mockValues.nextDate());

		ModuleEntity moduleEntity = new ModuleEntity();
		
		// When
		moduleServiceMapper.mapModuleToModuleEntity(module, moduleEntity);
		
		// Then
		assertEquals(module.getNiveau(), moduleEntity.getNiveau());
		assertEquals(module.getIdConponenet(), moduleEntity.getIdConponenet());
		assertEquals(module.getDomaine(), moduleEntity.getDomaine());
		assertEquals(module.getDateCreation(), moduleEntity.getDateCreation());
		assertEquals(module.getDateMaj(), moduleEntity.getDateMaj());
	}

}