/*
 * Created on 29 déc. 2015 ( Time 20:53:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
