/*
 * Created on 29 d�c. 2015 ( Time 20:53:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.immo.bean.Bien;
import com.immo.bean.Module;
import com.immo.bean.Profil;
import com.immo.bean.Projet;
import com.immo.bean.Tranche;
import com.immo.bean.jpa.BienEntity;
import com.immo.bean.jpa.ModuleEntity;
import com.immo.bean.jpa.ProfilEntity;
import com.immo.bean.jpa.ProjetEntity;
import com.immo.bean.jpa.TrancheEntity;

import java.util.Date;
import com.immo.business.service.BienService;
import com.immo.business.service.mapping.BienServiceMapper;
import com.immo.business.service.mapping.ProjetServiceMapper;
import com.immo.business.service.mapping.TrancheServiceMapper;
import com.immo.data.repository.jpa.BienJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of BienService
 */
@Component
@Transactional
public class BienServiceImpl implements BienService {

	@Resource
	private BienJpaRepository bienJpaRepository;

	@Resource
	private BienServiceMapper bienServiceMapper;
	
	@Resource
	private ProjetServiceMapper projetServiceMapper;
	
	@Resource
	private TrancheServiceMapper trancheServiceMapper;
	
	@Override
	public Bien findById(Long id) {
		BienEntity bienEntity = bienJpaRepository.findOne(id);
		return bienServiceMapper.mapBienEntityToBien(bienEntity);
	}

	@Override
	public List<Bien> findAll() {
		Iterable<BienEntity> entities = bienJpaRepository.findAll();
		List<Bien> beans = new ArrayList<Bien>();
		for(BienEntity bienEntity : entities) {
			beans.add(bienServiceMapper.mapBienEntityToBien(bienEntity));
		}
		return beans;
	}

	@Override
	public Bien save(Bien bien) {
		return update(bien) ;
	}

	@Override
	public Bien create(Bien bien) {
		/*BienEntity bienEntity = bienJpaRepository.findOne(bien.getId());
		if( bienEntity != null ) {
			throw new IllegalStateException("already.exists");
		}*/
		BienEntity bienEntity = new BienEntity();
		bienServiceMapper.mapBienToBienEntity(bien, bienEntity);
		BienEntity bienEntitySaved = bienJpaRepository.save(bienEntity);
		return bienServiceMapper.mapBienEntityToBien(bienEntitySaved);
	}

	@Override
	public Bien update(Bien bien) {
		BienEntity bienEntity = bienJpaRepository.findOne(bien.getId());
		System.out.println("bien : "+ bienEntity.getId() );
		System.out.println("bien : "+ bien.getDenomination() );
		bienServiceMapper.mapBienToBienEntity(bien, bienEntity);
		BienEntity bienEntitySaved = bienJpaRepository.save(bienEntity);
		return bienServiceMapper.mapBienEntityToBien(bienEntitySaved);
	}

	@Override
	public void delete(Long id) {
		bienJpaRepository.delete(id);
	}

	public BienJpaRepository getBienJpaRepository() {
		return bienJpaRepository;
	}

	public void setBienJpaRepository(BienJpaRepository bienJpaRepository) {
		this.bienJpaRepository = bienJpaRepository;
	}

	public BienServiceMapper getBienServiceMapper() {
		return bienServiceMapper;
	}

	public void setBienServiceMapper(BienServiceMapper bienServiceMapper) {
		this.bienServiceMapper = bienServiceMapper;
	}

	
	@Override
	public List<Bien> findBienByProjet(Projet p) {
		ProjetEntity projetEntity = new ProjetEntity();
		projetServiceMapper.mapProjetToProjetEntity(p, projetEntity);
		Iterable<BienEntity> entities = bienJpaRepository.findBienByProjet(projetEntity);
		List<Bien> beans = new ArrayList<Bien>();
		for(BienEntity bienEntity : entities) {
			beans.add(bienServiceMapper.mapBienEntityToBien(bienEntity));
		}
		return beans;
	}
	
	@Override
	public List<Bien> findBienByTranche(Tranche t) {
		TrancheEntity trancheEntity = new TrancheEntity();
		trancheServiceMapper.mapTrancheToTrancheEntity(t, trancheEntity);
		Iterable<BienEntity> entities = bienJpaRepository.findBienByTranche(trancheEntity);
		List<Bien> beans = new ArrayList<Bien>();
		for(BienEntity bienEntity : entities) {
			beans.add(bienServiceMapper.mapBienEntityToBien(bienEntity));
		}
		return beans;
	}
	
	@Override
	public List<Object>  etatBien(){
		List<Object> bean =  bienJpaRepository.etatBien();
		return bean;
	}
}
