/*
 * Created on 29 d�c. 2015 ( Time 20:53:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.immo.bean.Client;
import com.immo.bean.Dossier;
import com.immo.bean.DossierClient;
import com.immo.bean.Module;
import com.immo.bean.Profil;
import com.immo.bean.jpa.ClientEntity;
import com.immo.bean.jpa.DossierClientEntity;
import com.immo.bean.jpa.DossierEntity;
import com.immo.bean.jpa.ModuleEntity;
import com.immo.bean.jpa.ProfilEntity;
import com.immo.business.service.DossierClientService;
import com.immo.business.service.mapping.ClientServiceMapper;
import com.immo.business.service.mapping.DossierClientServiceMapper;
import com.immo.business.service.mapping.DossierServiceMapper;
import com.immo.data.repository.jpa.DossierClientJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of DossierClientService
 */
@Component
@Transactional
public class DossierClientServiceImpl implements DossierClientService {

	@Resource
	private DossierClientJpaRepository dossierClientJpaRepository;

	@Resource
	private DossierClientServiceMapper dossierClientServiceMapper;
	
	@Resource
	private DossierServiceMapper dossierServiceMapper;
	
	@Resource
	private ClientServiceMapper clientServiceMapper;
	
	@Override
	public DossierClient findById(Long id) {
		DossierClientEntity dossierClientEntity = dossierClientJpaRepository.findOne(id);
		return dossierClientServiceMapper.mapDossierClientEntityToDossierClient(dossierClientEntity);
	}
	
	@Override
	public List<DossierClient> findByDossier(Long id) {
		Iterable<DossierClientEntity> entities = dossierClientJpaRepository.findAll();
		List<DossierClient> beans = new ArrayList<DossierClient>();
		for(DossierClientEntity dossierClientEntity : entities) {
			if(dossierClientEntity.getDossier().getId()==id)
			beans.add(dossierClientServiceMapper.mapDossierClientEntityToDossierClient(dossierClientEntity));
		}
		return beans;
	}
	
	
	
	@Override
	public List<DossierClient> findAll() {
		Iterable<DossierClientEntity> entities = dossierClientJpaRepository.findAll();
		List<DossierClient> beans = new ArrayList<DossierClient>();
		for(DossierClientEntity dossierClientEntity : entities) {
			beans.add(dossierClientServiceMapper.mapDossierClientEntityToDossierClient(dossierClientEntity));
		}
		return beans;
	}

	@Override
	public DossierClient save(DossierClient dossierClient) {
		return update(dossierClient) ;
	}

	@Override
	public DossierClient create(DossierClient dossierClient) {
		DossierClientEntity dossierClientEntity = dossierClientJpaRepository.findOne(dossierClient.getId());
		if( dossierClientEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		dossierClientEntity = new DossierClientEntity();
		dossierClientServiceMapper.mapDossierClientToDossierClientEntity(dossierClient, dossierClientEntity);
		DossierClientEntity dossierClientEntitySaved = dossierClientJpaRepository.save(dossierClientEntity);
		return dossierClientServiceMapper.mapDossierClientEntityToDossierClient(dossierClientEntitySaved);
	}

	@Override
	public DossierClient update(DossierClient dossierClient) {
		DossierClientEntity dossierClientEntity = dossierClientJpaRepository.findOne(dossierClient.getId());
		dossierClientServiceMapper.mapDossierClientToDossierClientEntity(dossierClient, dossierClientEntity);
		DossierClientEntity dossierClientEntitySaved = dossierClientJpaRepository.save(dossierClientEntity);
		return dossierClientServiceMapper.mapDossierClientEntityToDossierClient(dossierClientEntitySaved);
	}

	@Override
	public void delete(Long id) {
		dossierClientJpaRepository.delete(id);
	}

	public DossierClientJpaRepository getDossierClientJpaRepository() {
		return dossierClientJpaRepository;
	}

	public void setDossierClientJpaRepository(DossierClientJpaRepository dossierClientJpaRepository) {
		this.dossierClientJpaRepository = dossierClientJpaRepository;
	}

	public DossierClientServiceMapper getDossierClientServiceMapper() {
		return dossierClientServiceMapper;
	}

	public void setDossierClientServiceMapper(DossierClientServiceMapper dossierClientServiceMapper) {
		this.dossierClientServiceMapper = dossierClientServiceMapper;
	}

	@Override
	public List<Client> findClientByDossier(Dossier d) {
		DossierEntity dossierEntity = new DossierEntity();
		dossierServiceMapper.mapDossierToDossierEntity(d, dossierEntity);
		Iterable<ClientEntity> entities = dossierClientJpaRepository.findClientByDossier(dossierEntity);
		List<Client> beans = new ArrayList<Client>();
		for(ClientEntity clientEntity : entities) {
			beans.add(clientServiceMapper.mapClientEntityToClient(clientEntity));
		}
		return beans;
	}
}
