/*
 * Created on 29 d�c. 2015 ( Time 20:53:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.immo.bean.Dossier;
import com.immo.bean.Recette;
import com.immo.bean.jpa.DossierEntity;
import com.immo.bean.jpa.RecetteEntity;
import java.util.Date;
import com.immo.business.service.RecetteService;
import com.immo.business.service.mapping.DossierServiceMapper;
import com.immo.business.service.mapping.RecetteServiceMapper;
import com.immo.data.repository.jpa.RecetteJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of RecetteService
 */
@Component
@Transactional
public class RecetteServiceImpl implements RecetteService {

	@Resource
	private RecetteJpaRepository recetteJpaRepository;

	@Resource
	private RecetteServiceMapper recetteServiceMapper;
	
	@Resource
	private DossierServiceMapper dossierServiceMapper;
	
	@Override
	public Recette findById(Long id) {
		RecetteEntity recetteEntity = recetteJpaRepository.findOne(id);
		return recetteServiceMapper.mapRecetteEntityToRecette(recetteEntity);
	}

	@Override
	public List<Recette> findAll() {
		Iterable<RecetteEntity> entities = recetteJpaRepository.findAll();
		List<Recette> beans = new ArrayList<Recette>();
		for(RecetteEntity recetteEntity : entities) {
			beans.add(recetteServiceMapper.mapRecetteEntityToRecette(recetteEntity));
		}
		return beans;
	}

	@Override
	public Recette save(Recette recette) {
		return update(recette) ;
	}

	@Override
	public Recette create(Recette recette) {
		/*RecetteEntity recetteEntity = recetteJpaRepository.findOne(recette.getId());
		if( recetteEntity != null ) {
			throw new IllegalStateException("already.exists");
		}*/
		RecetteEntity recetteEntity = new RecetteEntity();
		recetteServiceMapper.mapRecetteToRecetteEntity(recette, recetteEntity);
		RecetteEntity recetteEntitySaved = recetteJpaRepository.save(recetteEntity);
		return recetteServiceMapper.mapRecetteEntityToRecette(recetteEntitySaved);
	}

	@Override
	public Recette update(Recette recette) {
		RecetteEntity recetteEntity = recetteJpaRepository.findOne(recette.getId());
		recetteServiceMapper.mapRecetteToRecetteEntity(recette, recetteEntity);
		RecetteEntity recetteEntitySaved = recetteJpaRepository.save(recetteEntity);
		return recetteServiceMapper.mapRecetteEntityToRecette(recetteEntitySaved);
	}

	@Override
	public void delete(Long id) {
		recetteJpaRepository.delete(id);
	}

	public RecetteJpaRepository getRecetteJpaRepository() {
		return recetteJpaRepository;
	}

	public void setRecetteJpaRepository(RecetteJpaRepository recetteJpaRepository) {
		this.recetteJpaRepository = recetteJpaRepository;
	}

	public RecetteServiceMapper getRecetteServiceMapper() {
		return recetteServiceMapper;
	}

	public void setRecetteServiceMapper(RecetteServiceMapper recetteServiceMapper) {
		this.recetteServiceMapper = recetteServiceMapper;
	}
	
	@Override
	public List<Recette> findByDossier(Dossier d) {
		DossierEntity dossierEntity = new DossierEntity();
		dossierServiceMapper.mapDossierToDossierEntity(d, dossierEntity);
		Iterable<RecetteEntity> entities = recetteJpaRepository.findByDossier(dossierEntity);
		List<Recette> beans = new ArrayList<Recette>();
		for(RecetteEntity recetteEntity : entities) {
			beans.add(recetteServiceMapper.mapRecetteEntityToRecette(recetteEntity));
		}
		return beans;
	}

	@Override
	public List<Recette> findByNumAndBanque(Recette recette) {
		
		Iterable<RecetteEntity> entities = recetteJpaRepository.findByNumAndBanque(recette.getNumRecette(), recette.getBanque());
		List<Recette> beans = new ArrayList<Recette>();
		for(RecetteEntity recetteEntity : entities) {
			beans.add(recetteServiceMapper.mapRecetteEntityToRecette(recetteEntity));
		}
		return beans;
	}
	
	@Override
	public Recette annulePaiement(Recette recette) {
		recette.setEtat("annule");
		RecetteEntity recetteEntity = recetteJpaRepository.findOne(recette.getId());
		recetteServiceMapper.mapRecetteToRecetteEntity(recette, recetteEntity);
		RecetteEntity recetteEntitySaved = recetteJpaRepository.save(recetteEntity);
		return recetteServiceMapper.mapRecetteEntityToRecette(recetteEntitySaved);
	}


}
