/*
 * Created on 29 d�c. 2015 ( Time 20:53:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.immo.bean.Tranche;
import com.immo.bean.jpa.TrancheEntity;
import java.util.Date;
import java.util.List;
import com.immo.business.service.TrancheService;
import com.immo.business.service.mapping.TrancheServiceMapper;
import com.immo.data.repository.jpa.TrancheJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of TrancheService
 */
@Component
@Transactional
public class TrancheServiceImpl implements TrancheService {

	@Resource
	private TrancheJpaRepository trancheJpaRepository;

	@Resource
	private TrancheServiceMapper trancheServiceMapper;
	
	@Override
	public Tranche findById(Long id) {
		TrancheEntity trancheEntity = trancheJpaRepository.findOne(id);
		return trancheServiceMapper.mapTrancheEntityToTranche(trancheEntity);
	}

	@Override
	public List<Tranche> findAll() {
		Iterable<TrancheEntity> entities = trancheJpaRepository.findAll();
		List<Tranche> beans = new ArrayList<Tranche>();
		for(TrancheEntity trancheEntity : entities) {
			beans.add(trancheServiceMapper.mapTrancheEntityToTranche(trancheEntity));
		}
		return beans;
	}

	@Override
	public Tranche save(Tranche tranche) {
		return update(tranche) ;
	}

	@Override
	public Tranche create(Tranche tranche) {
		/*TrancheEntity trancheEntity = trancheJpaRepository.findOne(tranche.getId());
		if( trancheEntity != null ) {
			throw new IllegalStateException("already.exists");
		}*/
		TrancheEntity trancheEntity = new TrancheEntity();
		trancheServiceMapper.mapTrancheToTrancheEntity(tranche, trancheEntity);
		TrancheEntity trancheEntitySaved = trancheJpaRepository.save(trancheEntity);
		return trancheServiceMapper.mapTrancheEntityToTranche(trancheEntitySaved);
	}

	@Override
	public Tranche update(Tranche tranche) {
		TrancheEntity trancheEntity = trancheJpaRepository.findOne(tranche.getId());
		trancheServiceMapper.mapTrancheToTrancheEntity(tranche, trancheEntity);
		TrancheEntity trancheEntitySaved = trancheJpaRepository.save(trancheEntity);
		return trancheServiceMapper.mapTrancheEntityToTranche(trancheEntitySaved);
	}

	@Override
	public void delete(Long id) {
		trancheJpaRepository.delete(id);
	}

	public TrancheJpaRepository getTrancheJpaRepository() {
		return trancheJpaRepository;
	}

	public void setTrancheJpaRepository(TrancheJpaRepository trancheJpaRepository) {
		this.trancheJpaRepository = trancheJpaRepository;
	}

	public TrancheServiceMapper getTrancheServiceMapper() {
		return trancheServiceMapper;
	}

	public void setTrancheServiceMapper(TrancheServiceMapper trancheServiceMapper) {
		this.trancheServiceMapper = trancheServiceMapper;
	}

}
