/*
 * Created on 29 d�c. 2015 ( Time 20:53:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.immo.bean.Client;
import com.immo.bean.Projet;
import com.immo.bean.Tranche;
import com.immo.bean.Utilisateur;
import com.immo.bean.UtilisateurTranche;
import com.immo.bean.jpa.ClientEntity;
import com.immo.bean.jpa.DossierEntity;
import com.immo.bean.jpa.ProjetEntity;
import com.immo.bean.jpa.TrancheEntity;
import com.immo.bean.jpa.UtilisateurEntity;
import com.immo.bean.jpa.UtilisateurTrancheEntity;
import java.util.Date;
import com.immo.business.service.UtilisateurTrancheService;
import com.immo.business.service.mapping.ProjetServiceMapper;
import com.immo.business.service.mapping.TrancheServiceMapper;
import com.immo.business.service.mapping.UtilisateurServiceMapper;
import com.immo.business.service.mapping.UtilisateurTrancheServiceMapper;
import com.immo.data.repository.jpa.UtilisateurTrancheJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of UtilisateurTrancheService
 */
@Component
@Transactional
public class UtilisateurTrancheServiceImpl implements UtilisateurTrancheService {

	@Resource
	private UtilisateurTrancheJpaRepository utilisateurTrancheJpaRepository;

	@Resource
	private UtilisateurTrancheServiceMapper utilisateurTrancheServiceMapper;
	
	@Resource
	private UtilisateurServiceMapper utilisateurServiceMapper;
	
	@Resource
	private ProjetServiceMapper projetServiceMapper;
	
	@Resource
	private TrancheServiceMapper trancheServiceMapper;
	
	@Override
	public UtilisateurTranche findById(Long id) {
		UtilisateurTrancheEntity utilisateurTrancheEntity = utilisateurTrancheJpaRepository.findOne(id);
		return utilisateurTrancheServiceMapper.mapUtilisateurTrancheEntityToUtilisateurTranche(utilisateurTrancheEntity);
	}

	@Override
	public List<UtilisateurTranche> findAll() {
		Iterable<UtilisateurTrancheEntity> entities = utilisateurTrancheJpaRepository.findAll();
		List<UtilisateurTranche> beans = new ArrayList<UtilisateurTranche>();
		for(UtilisateurTrancheEntity utilisateurTrancheEntity : entities) {
			beans.add(utilisateurTrancheServiceMapper.mapUtilisateurTrancheEntityToUtilisateurTranche(utilisateurTrancheEntity));
		}
		return beans;
	}

	@Override
	public UtilisateurTranche save(UtilisateurTranche utilisateurTranche) {
		return update(utilisateurTranche) ;
	}

	@Override
	public UtilisateurTranche create(UtilisateurTranche utilisateurTranche) {
		UtilisateurTrancheEntity utilisateurTrancheEntity = utilisateurTrancheJpaRepository.findOne(utilisateurTranche.getId());
		if( utilisateurTrancheEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		utilisateurTrancheEntity = new UtilisateurTrancheEntity();
		utilisateurTrancheServiceMapper.mapUtilisateurTrancheToUtilisateurTrancheEntity(utilisateurTranche, utilisateurTrancheEntity);
		UtilisateurTrancheEntity utilisateurTrancheEntitySaved = utilisateurTrancheJpaRepository.save(utilisateurTrancheEntity);
		return utilisateurTrancheServiceMapper.mapUtilisateurTrancheEntityToUtilisateurTranche(utilisateurTrancheEntitySaved);
	}

	@Override
	public UtilisateurTranche update(UtilisateurTranche utilisateurTranche) {
		UtilisateurTrancheEntity utilisateurTrancheEntity = utilisateurTrancheJpaRepository.findOne(utilisateurTranche.getId());
		utilisateurTrancheServiceMapper.mapUtilisateurTrancheToUtilisateurTrancheEntity(utilisateurTranche, utilisateurTrancheEntity);
		UtilisateurTrancheEntity utilisateurTrancheEntitySaved = utilisateurTrancheJpaRepository.save(utilisateurTrancheEntity);
		return utilisateurTrancheServiceMapper.mapUtilisateurTrancheEntityToUtilisateurTranche(utilisateurTrancheEntitySaved);
	}

	@Override
	public void delete(Long id) {
		utilisateurTrancheJpaRepository.delete(id);
	}

	public UtilisateurTrancheJpaRepository getUtilisateurTrancheJpaRepository() {
		return utilisateurTrancheJpaRepository;
	}

	public void setUtilisateurTrancheJpaRepository(UtilisateurTrancheJpaRepository utilisateurTrancheJpaRepository) {
		this.utilisateurTrancheJpaRepository = utilisateurTrancheJpaRepository;
	}

	public UtilisateurTrancheServiceMapper getUtilisateurTrancheServiceMapper() {
		return utilisateurTrancheServiceMapper;
	}

	public void setUtilisateurTrancheServiceMapper(UtilisateurTrancheServiceMapper utilisateurTrancheServiceMapper) {
		this.utilisateurTrancheServiceMapper = utilisateurTrancheServiceMapper;
	}
	
	

	public UtilisateurServiceMapper getUtilisateurServiceMapper() {
		return utilisateurServiceMapper;
	}

	public void setUtilisateurServiceMapper(UtilisateurServiceMapper utilisateurServiceMapper) {
		this.utilisateurServiceMapper = utilisateurServiceMapper;
	}

	@Override
	public List<Projet> findProjetByUser(Utilisateur u) {
		// TODO Auto-generated method stub
		UtilisateurEntity utilisateurEntity = new UtilisateurEntity();
		utilisateurServiceMapper.mapUtilisateurToUtilisateurEntity(u, utilisateurEntity);
		Iterable<ProjetEntity> entities = utilisateurTrancheJpaRepository.findProjetByUser(utilisateurEntity);
		List<Projet> beans = new ArrayList<Projet>();
		for(ProjetEntity projetEntity : entities) {
			beans.add(projetServiceMapper.mapProjetEntityToProjet(projetEntity));
		}
		return beans;
	}

	@Override
	public List<Tranche> findTrancheByUser(Utilisateur u) {
		// TODO Auto-generated method stub
		UtilisateurEntity utilisateurEntity = new UtilisateurEntity();
		utilisateurServiceMapper.mapUtilisateurToUtilisateurEntity(u, utilisateurEntity);
		Iterable<TrancheEntity> entities = utilisateurTrancheJpaRepository.findTrancheByUser(utilisateurEntity);
		List<Tranche> beans = new ArrayList<Tranche>();
		for(TrancheEntity trancheEntity : entities) {
			beans.add(trancheServiceMapper.mapTrancheEntityToTranche(trancheEntity));
		}
		return beans;
	}

}
