/*
 * Created on 29 déc. 2015 ( Time 20:50:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.listitem;

import com.immo.bean.Client;
import com.immo.web.common.ListItem;

public class ClientListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ClientListItem(Client client) {
		super();

		this.value = ""
			 + client.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = client.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
