/*
 * Created on 29 déc. 2015 ( Time 20:50:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.listitem;

import com.immo.bean.Module;
import com.immo.web.common.ListItem;

public class ModuleListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ModuleListItem(Module module) {
		super();

		this.value = ""
			 + module.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = module.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
