/*
 * Created on 29 déc. 2015 ( Time 20:50:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.listitem;

import com.immo.bean.ModuleProfil;
import com.immo.web.common.ListItem;

public class ModuleProfilListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ModuleProfilListItem(ModuleProfil moduleProfil) {
		super();

		this.value = ""
			 + moduleProfil.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = moduleProfil.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
