/*
 * Created on 29 déc. 2015 ( Time 20:53:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.listitem;

import com.immo.bean.Profil;
import com.immo.web.common.ListItem;

public class ProfilListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ProfilListItem(Profil profil) {
		super();

		this.value = ""
			 + profil.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = profil.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
