/*
 * Created on 29 déc. 2015 ( Time 20:53:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.listitem;

import com.immo.bean.UtilisateurTranche;
import com.immo.web.common.ListItem;

public class UtilisateurTrancheListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UtilisateurTrancheListItem(UtilisateurTranche utilisateurTranche) {
		super();

		this.value = ""
			 + utilisateurTranche.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = utilisateurTranche.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
