/*
 * Created on 29 déc. 2015 ( Time 20:53:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.listitem;

import com.immo.bean.Utilisateur;
import com.immo.web.common.ListItem;

public class UtilisateurListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UtilisateurListItem(Utilisateur utilisateur) {
		super();

		this.value = ""
			 + utilisateur.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = utilisateur.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
