/*
 * Created on 29 déc. 2015 ( Time 20:50:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.immo.web.common.AbstractController;
import com.immo.web.common.FormMode;
import com.immo.web.common.Message;
import com.immo.web.common.MessageType;

//--- Entities
import com.immo.bean.Bien;
import com.immo.bean.Reference;
import com.immo.bean.Tranche;

//--- Services 
import com.immo.business.service.BienService;
import com.immo.business.service.ReferenceService;
import com.immo.business.service.TrancheService;

//--- List Items 
import com.immo.web.listitem.ReferenceListItem;
import com.immo.web.listitem.TrancheListItem;

/**
 * Spring MVC controller for 'Bien' management.
 */
@Controller
@RequestMapping("/bien")
public class BienController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "bien";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "bien/form";
	private static final String JSP_LIST   = "bien/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/bien/create";
	private static final String SAVE_ACTION_UPDATE   = "/bien/update";

	//--- Main entity service
	@Resource
    private BienService bienService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ReferenceService referenceService; // Injected by Spring
	@Resource
    private TrancheService trancheService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BienController() {
		super(BienController.class, MAIN_ENTITY_NAME );
		log("BienController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Reference"
	 * @param model
	 */
	private void populateListOfReferenceItems(Model model) {
		List<Reference> list = referenceService.findAll();
		List<ReferenceListItem> items = new LinkedList<ReferenceListItem>();
		for ( Reference reference : list ) {
			items.add(new ReferenceListItem( reference ) );
		}
		model.addAttribute("listOfReferenceItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Tranche"
	 * @param model
	 */
	private void populateListOfTrancheItems(Model model) {
		List<Tranche> list = trancheService.findAll();
		List<TrancheListItem> items = new LinkedList<TrancheListItem>();
		for ( Tranche tranche : list ) {
			items.add(new TrancheListItem( tranche ) );
		}
		model.addAttribute("listOfTrancheItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param bien
	 */
	private void populateModel(Model model, Bien bien, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, bien);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfReferenceItems(model);
			populateListOfTrancheItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfTrancheItems(model);
			populateListOfReferenceItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Bien found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Bien> list = bienService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Bien
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Bien bien = new Bien();	
		populateModel( model, bien, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Bien
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Long id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Bien bien = bienService.findById(id);
		populateModel( model, bien, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bien  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Bien bien, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Bien bienCreated = bienService.create(bien); 
				model.addAttribute(MAIN_ENTITY_NAME, bienCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, bien.getId() );
			} else {
				populateModel( model, bien, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "bien.error.create", e);
			populateModel( model, bien, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bien  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Bien bien, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Bien bienSaved = bienService.update(bien);
				model.addAttribute(MAIN_ENTITY_NAME, bienSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, bien.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, bien, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "bien.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, bien, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Long id) {
		log("Action 'delete'" );
		try {
			bienService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "bien.error.delete", e);
		}
		return redirectToList();
	}

}
