/*
 * Created on 29 déc. 2015 ( Time 20:53:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.immo.web.common.AbstractController;
import com.immo.web.common.FormMode;
import com.immo.web.common.Message;
import com.immo.web.common.MessageType;

//--- Entities
import com.immo.bean.Utilisateur;
import com.immo.bean.Profil;

//--- Services 
import com.immo.business.service.UtilisateurService;
import com.immo.business.service.ProfilService;

//--- List Items 
import com.immo.web.listitem.ProfilListItem;

/**
 * Spring MVC controller for 'Utilisateur' management.
 */
@Controller
@RequestMapping("/utilisateur")
public class UtilisateurController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "utilisateur";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "utilisateur/form";
	private static final String JSP_LIST   = "utilisateur/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/utilisateur/create";
	private static final String SAVE_ACTION_UPDATE   = "/utilisateur/update";

	//--- Main entity service
	@Resource
    private UtilisateurService utilisateurService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ProfilService profilService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public UtilisateurController() {
		super(UtilisateurController.class, MAIN_ENTITY_NAME );
		log("UtilisateurController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Profil"
	 * @param model
	 */
	private void populateListOfProfilItems(Model model) {
		List<Profil> list = profilService.findAll();
		List<ProfilListItem> items = new LinkedList<ProfilListItem>();
		for ( Profil profil : list ) {
			items.add(new ProfilListItem( profil ) );
		}
		model.addAttribute("listOfProfilItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param utilisateur
	 */
	private void populateModel(Model model, Utilisateur utilisateur, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, utilisateur);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfProfilItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfProfilItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Utilisateur found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Utilisateur> list = utilisateurService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Utilisateur
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Utilisateur utilisateur = new Utilisateur();	
		populateModel( model, utilisateur, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Utilisateur
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Long id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Utilisateur utilisateur = utilisateurService.findById(id);
		populateModel( model, utilisateur, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param utilisateur  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Utilisateur utilisateur, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Utilisateur utilisateurCreated = utilisateurService.create(utilisateur); 
				model.addAttribute(MAIN_ENTITY_NAME, utilisateurCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, utilisateur.getId() );
			} else {
				populateModel( model, utilisateur, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "utilisateur.error.create", e);
			populateModel( model, utilisateur, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param utilisateur  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Utilisateur utilisateur, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Utilisateur utilisateurSaved = utilisateurService.update(utilisateur);
				model.addAttribute(MAIN_ENTITY_NAME, utilisateurSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, utilisateur.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, utilisateur, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "utilisateur.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, utilisateur, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Long id) {
		log("Action 'delete'" );
		try {
			utilisateurService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "utilisateur.error.delete", e);
		}
		return redirectToList();
	}

}
