/*
 * Created on 29 déc. 2015 ( Time 20:50:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Bien implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Long refTranche;

    @Size( max = 100 )
    private String denomination;


    private Long supProv;


    private Long supFinale;

    @Size( max = 100 )
    private String tf;

    @Size( max = 100 )
    private String tfMere;

    @Size( max = 100 )
    private String etat;


    private Long prixHt;


    private Long prixTtc;


    private Date dateLivraison;

    @Size( max = 100 )
    private String ilot;

    @Size( max = 100 )
    private String tantieme;

    @Size( max = 100 )
    private String quotePart;


    private Date datePermisHabiter;


    private Long mntTva;


    private Long echMnt1;


    private Long echMnt2;


    private Long echMnt3;


    private Long echMnt4;


    private Long echDelai1;


    private Long echDelai2;


    private Long echDelai3;


    private Long echDelai4;

    @Size( max = 30 )
    private String typeBien;

    @Size( max = 30 )
    private String niveau;

    @Size( max = 30 )
    private String numBien;

    @Size( max = 30 )
    private String immeuble;

    @Size( max = 30 )
    private String orientation;


    private Long supBalcon;


    private Date dateCreation;


    private Date dateMaj;


    private Long bienReference;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefTranche( Long refTranche ) {
        this.refTranche = refTranche;
    }
    public Long getRefTranche() {
        return this.refTranche;
    }

    public void setDenomination( String denomination ) {
        this.denomination = denomination;
    }
    public String getDenomination() {
        return this.denomination;
    }

    public void setSupProv( Long supProv ) {
        this.supProv = supProv;
    }
    public Long getSupProv() {
        return this.supProv;
    }

    public void setSupFinale( Long supFinale ) {
        this.supFinale = supFinale;
    }
    public Long getSupFinale() {
        return this.supFinale;
    }

    public void setTf( String tf ) {
        this.tf = tf;
    }
    public String getTf() {
        return this.tf;
    }

    public void setTfMere( String tfMere ) {
        this.tfMere = tfMere;
    }
    public String getTfMere() {
        return this.tfMere;
    }

    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    public void setPrixHt( Long prixHt ) {
        this.prixHt = prixHt;
    }
    public Long getPrixHt() {
        return this.prixHt;
    }

    public void setPrixTtc( Long prixTtc ) {
        this.prixTtc = prixTtc;
    }
    public Long getPrixTtc() {
        return this.prixTtc;
    }

    public void setDateLivraison( Date dateLivraison ) {
        this.dateLivraison = dateLivraison;
    }
    public Date getDateLivraison() {
        return this.dateLivraison;
    }

    public void setIlot( String ilot ) {
        this.ilot = ilot;
    }
    public String getIlot() {
        return this.ilot;
    }

    public void setTantieme( String tantieme ) {
        this.tantieme = tantieme;
    }
    public String getTantieme() {
        return this.tantieme;
    }

    public void setQuotePart( String quotePart ) {
        this.quotePart = quotePart;
    }
    public String getQuotePart() {
        return this.quotePart;
    }

    public void setDatePermisHabiter( Date datePermisHabiter ) {
        this.datePermisHabiter = datePermisHabiter;
    }
    public Date getDatePermisHabiter() {
        return this.datePermisHabiter;
    }

    public void setMntTva( Long mntTva ) {
        this.mntTva = mntTva;
    }
    public Long getMntTva() {
        return this.mntTva;
    }

    public void setEchMnt1( Long echMnt1 ) {
        this.echMnt1 = echMnt1;
    }
    public Long getEchMnt1() {
        return this.echMnt1;
    }

    public void setEchMnt2( Long echMnt2 ) {
        this.echMnt2 = echMnt2;
    }
    public Long getEchMnt2() {
        return this.echMnt2;
    }

    public void setEchMnt3( Long echMnt3 ) {
        this.echMnt3 = echMnt3;
    }
    public Long getEchMnt3() {
        return this.echMnt3;
    }

    public void setEchMnt4( Long echMnt4 ) {
        this.echMnt4 = echMnt4;
    }
    public Long getEchMnt4() {
        return this.echMnt4;
    }

    public void setEchDelai1( Long echDelai1 ) {
        this.echDelai1 = echDelai1;
    }
    public Long getEchDelai1() {
        return this.echDelai1;
    }

    public void setEchDelai2( Long echDelai2 ) {
        this.echDelai2 = echDelai2;
    }
    public Long getEchDelai2() {
        return this.echDelai2;
    }

    public void setEchDelai3( Long echDelai3 ) {
        this.echDelai3 = echDelai3;
    }
    public Long getEchDelai3() {
        return this.echDelai3;
    }

    public void setEchDelai4( Long echDelai4 ) {
        this.echDelai4 = echDelai4;
    }
    public Long getEchDelai4() {
        return this.echDelai4;
    }

    public void setTypeBien( String typeBien ) {
        this.typeBien = typeBien;
    }
    public String getTypeBien() {
        return this.typeBien;
    }

    public void setNiveau( String niveau ) {
        this.niveau = niveau;
    }
    public String getNiveau() {
        return this.niveau;
    }

    public void setNumBien( String numBien ) {
        this.numBien = numBien;
    }
    public String getNumBien() {
        return this.numBien;
    }

    public void setImmeuble( String immeuble ) {
        this.immeuble = immeuble;
    }
    public String getImmeuble() {
        return this.immeuble;
    }

    public void setOrientation( String orientation ) {
        this.orientation = orientation;
    }
    public String getOrientation() {
        return this.orientation;
    }

    public void setSupBalcon( Long supBalcon ) {
        this.supBalcon = supBalcon;
    }
    public Long getSupBalcon() {
        return this.supBalcon;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    public void setBienReference( Long bienReference ) {
        this.bienReference = bienReference;
    }
    public Long getBienReference() {
        return this.bienReference;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refTranche);
        sb.append("|");
        sb.append(denomination);
        sb.append("|");
        sb.append(supProv);
        sb.append("|");
        sb.append(supFinale);
        sb.append("|");
        sb.append(tf);
        sb.append("|");
        sb.append(tfMere);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(prixHt);
        sb.append("|");
        sb.append(prixTtc);
        sb.append("|");
        sb.append(dateLivraison);
        sb.append("|");
        sb.append(ilot);
        sb.append("|");
        sb.append(tantieme);
        sb.append("|");
        sb.append(quotePart);
        sb.append("|");
        sb.append(datePermisHabiter);
        sb.append("|");
        sb.append(mntTva);
        sb.append("|");
        sb.append(echMnt1);
        sb.append("|");
        sb.append(echMnt2);
        sb.append("|");
        sb.append(echMnt3);
        sb.append("|");
        sb.append(echMnt4);
        sb.append("|");
        sb.append(echDelai1);
        sb.append("|");
        sb.append(echDelai2);
        sb.append("|");
        sb.append(echDelai3);
        sb.append("|");
        sb.append(echDelai4);
        sb.append("|");
        sb.append(typeBien);
        sb.append("|");
        sb.append(niveau);
        sb.append("|");
        sb.append(numBien);
        sb.append("|");
        sb.append(immeuble);
        sb.append("|");
        sb.append(orientation);
        sb.append("|");
        sb.append(supBalcon);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(bienReference);
        return sb.toString(); 
    } 


}
