/*
 * Created on 29 d�c. 2015 ( Time 20:50:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Dossier implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Long refBien;

    @Size( max = 100 )
    private String commercial;

    @Size( max = 100 )
    private String etat;


    private Long refProjet;


    private Long refTranche;


    private Long typeDesistement;


    private Long dateDesistement;

    @Size( max = 100 )
    private String numDossDoc;


    private Long refConvention;


    private Long numVenteProjet;


    private Date dateCreation;


    private Date dateMaj;

    private Date dateFacturation;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefBien( Long refBien ) {
        this.refBien = refBien;
    }
    public Long getRefBien() {
        return this.refBien;
    }

    public void setCommercial( String commercial ) {
        this.commercial = commercial;
    }
    public String getCommercial() {
        return this.commercial;
    }

    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    public void setRefProjet( Long refProjet ) {
        this.refProjet = refProjet;
    }
    public Long getRefProjet() {
        return this.refProjet;
    }

    public void setRefTranche( Long refTranche ) {
        this.refTranche = refTranche;
    }
    public Long getRefTranche() {
        return this.refTranche;
    }

    public void setTypeDesistement( Long typeDesistement ) {
        this.typeDesistement = typeDesistement;
    }
    public Long getTypeDesistement() {
        return this.typeDesistement;
    }

    public void setDateDesistement( Long dateDesistement ) {
        this.dateDesistement = dateDesistement;
    }
    public Long getDateDesistement() {
        return this.dateDesistement;
    }

    public void setNumDossDoc( String numDossDoc ) {
        this.numDossDoc = numDossDoc;
    }
    public String getNumDossDoc() {
        return this.numDossDoc;
    }

    public void setRefConvention( Long refConvention ) {
        this.refConvention = refConvention;
    }
    public Long getRefConvention() {
        return this.refConvention;
    }

    public void setNumVenteProjet( Long numVenteProjet ) {
        this.numVenteProjet = numVenteProjet;
    }
    public Long getNumVenteProjet() {
        return this.numVenteProjet;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    public Date getDateFacturation() {
	return dateFacturation;
}

public void setDateFacturation(Date dateFacturation) {
	this.dateFacturation = dateFacturation;
}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 

		public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refBien);
        sb.append("|");
        sb.append(commercial);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(refProjet);
        sb.append("|");
        sb.append(refTranche);
        sb.append("|");
        sb.append(typeDesistement);
        sb.append("|");
        sb.append(dateDesistement);
        sb.append("|");
        sb.append(numDossDoc);
        sb.append("|");
        sb.append(refConvention);
        sb.append("|");
        sb.append(numVenteProjet);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(dateFacturation);
        return sb.toString(); 
    } 


}
