/*
 * Created on 29 déc. 2015 ( Time 20:50:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Echeance implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Long refDossier;


    private Long numero;


    private Date dateEcheance;


    private Long montant;

    @Size( max = 100 )
    private String observation;


    private Long pourcentage;


    private Date dateCreation;


    private Date dateMaj;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefDossier( Long refDossier ) {
        this.refDossier = refDossier;
    }
    public Long getRefDossier() {
        return this.refDossier;
    }

    public void setNumero( Long numero ) {
        this.numero = numero;
    }
    public Long getNumero() {
        return this.numero;
    }

    public void setDateEcheance( Date dateEcheance ) {
        this.dateEcheance = dateEcheance;
    }
    public Date getDateEcheance() {
        return this.dateEcheance;
    }

    public void setMontant( Long montant ) {
        this.montant = montant;
    }
    public Long getMontant() {
        return this.montant;
    }

    public void setObservation( String observation ) {
        this.observation = observation;
    }
    public String getObservation() {
        return this.observation;
    }

    public void setPourcentage( Long pourcentage ) {
        this.pourcentage = pourcentage;
    }
    public Long getPourcentage() {
        return this.pourcentage;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refDossier);
        sb.append("|");
        sb.append(numero);
        sb.append("|");
        sb.append(dateEcheance);
        sb.append("|");
        sb.append(montant);
        sb.append("|");
        sb.append(observation);
        sb.append("|");
        sb.append(pourcentage);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 


}
