/*
 * Created on 29 déc. 2015 ( Time 20:53:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.immo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Reference implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Long refTypeReference;

    @Size( max = 100 )
    private String libelle;


    private Long ordre;


    private Long refProjet;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefTypeReference( Long refTypeReference ) {
        this.refTypeReference = refTypeReference;
    }
    public Long getRefTypeReference() {
        return this.refTypeReference;
    }

    public void setLibelle( String libelle ) {
        this.libelle = libelle;
    }
    public String getLibelle() {
        return this.libelle;
    }

    public void setOrdre( Long ordre ) {
        this.ordre = ordre;
    }
    public Long getOrdre() {
        return this.ordre;
    }

    public void setRefProjet( Long refProjet ) {
        this.refProjet = refProjet;
    }
    public Long getRefProjet() {
        return this.refProjet;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refTypeReference);
        sb.append("|");
        sb.append(libelle);
        sb.append("|");
        sb.append(ordre);
        sb.append("|");
        sb.append(refProjet);
        return sb.toString(); 
    } 


}
