/*
 * Created on 29 d�c. 2015 ( Time 20:53:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "BIEN"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="BIEN", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BienEntity.countAll", query="SELECT COUNT(x) FROM BienEntity x" )
} )
public class BienEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="BIEN_SEQ", allocationSize=1)
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DENOMINATION", length=100)
    private String     denomination ;

    @Column(name="SUP_PROV")
    private Long       supProv      ;

    @Column(name="SUP_FINALE")
    private Long       supFinale    ;

    @Column(name="TF", length=100)
    private String     tf           ;

    @Column(name="TF_MERE", length=100)
    private String     tfMere       ;

    @Column(name="ETAT", length=100)
    private String     etat         ;

    @Column(name="PRIX_HT")
    private Long       prixHt       ;

    @Column(name="PRIX_TTC")
    private Long       prixTtc      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_LIVRAISON")
    private Date       dateLivraison ;

    @Column(name="ILOT", length=100)
    private String     ilot         ;

    @Column(name="TANTIEME", length=100)
    private String     tantieme     ;

    @Column(name="QUOTE_PART", length=100)
    private String     quotePart    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_PERMIS_HABITER")
    private Date       datePermisHabiter ;

    @Column(name="MNT_TVA")
    private Long       mntTva       ;

    @Column(name="ECH_MNT_1")
    private Long       echMnt1      ;

    @Column(name="ECH_MNT_2")
    private Long       echMnt2      ;

    @Column(name="ECH_MNT_3")
    private Long       echMnt3      ;

    @Column(name="ECH_MNT_4")
    private Long       echMnt4      ;

    @Column(name="ECH_DELAI_1")
    private Long       echDelai1    ;

    @Column(name="ECH_DELAI_2")
    private Long       echDelai2    ;

    @Column(name="ECH_DELAI_3")
    private Long       echDelai3    ;

    @Column(name="ECH_DELAI_4")
    private Long       echDelai4    ;

    @Column(name="TYPE_BIEN", length=30)
    private String     typeBien     ;

    @Column(name="NIVEAU", length=30)
    private String     niveau       ;

    @Column(name="NUM_BIEN", length=30)
    private String     numBien      ;

    @Column(name="IMMEUBLE", length=30)
    private String     immeuble     ;

    @Column(name="ORIENTATION", length=30)
    private String     orientation  ;

    @Column(name="SUP_BALCON")
    private Long       supBalcon    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

	// "refTranche" (column "REF_TRANCHE") is not defined by itself because used as FK in a link 
	// "bienReference" (column "BIEN_REFERENCE") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="BIEN_REFERENCE", referencedColumnName="ID")
    private ReferenceEntity reference   ;

    @ManyToOne
    @JoinColumn(name="REF_TRANCHE", referencedColumnName="ID")
    private TrancheEntity tranche     ;

    @OneToMany(mappedBy="bien", targetEntity=TraceDossierEntity.class)
    private List<TraceDossierEntity> listOfTraceDossier;
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BienEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DENOMINATION ( VARCHAR2 ) 
    public void setDenomination( String denomination ) {
        this.denomination = denomination;
    }
    public String getDenomination() {
        return this.denomination;
    }

    //--- DATABASE MAPPING : SUP_PROV ( NUMBER ) 
    public void setSupProv( Long supProv ) {
        this.supProv = supProv;
    }
    public Long getSupProv() {
        return this.supProv;
    }

    //--- DATABASE MAPPING : SUP_FINALE ( NUMBER ) 
    public void setSupFinale( Long supFinale ) {
        this.supFinale = supFinale;
    }
    public Long getSupFinale() {
        return this.supFinale;
    }

    //--- DATABASE MAPPING : TF ( VARCHAR2 ) 
    public void setTf( String tf ) {
        this.tf = tf;
    }
    public String getTf() {
        return this.tf;
    }

    //--- DATABASE MAPPING : TF_MERE ( VARCHAR2 ) 
    public void setTfMere( String tfMere ) {
        this.tfMere = tfMere;
    }
    public String getTfMere() {
        return this.tfMere;
    }

    //--- DATABASE MAPPING : ETAT ( VARCHAR2 ) 
    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    //--- DATABASE MAPPING : PRIX_HT ( NUMBER ) 
    public void setPrixHt( Long prixHt ) {
        this.prixHt = prixHt;
    }
    public Long getPrixHt() {
        return this.prixHt;
    }

    //--- DATABASE MAPPING : PRIX_TTC ( NUMBER ) 
    public void setPrixTtc( Long prixTtc ) {
        this.prixTtc = prixTtc;
    }
    public Long getPrixTtc() {
        return this.prixTtc;
    }

    //--- DATABASE MAPPING : DATE_LIVRAISON ( DATE ) 
    public void setDateLivraison( Date dateLivraison ) {
        this.dateLivraison = dateLivraison;
    }
    public Date getDateLivraison() {
        return this.dateLivraison;
    }

    //--- DATABASE MAPPING : ILOT ( VARCHAR2 ) 
    public void setIlot( String ilot ) {
        this.ilot = ilot;
    }
    public String getIlot() {
        return this.ilot;
    }

    //--- DATABASE MAPPING : TANTIEME ( VARCHAR2 ) 
    public void setTantieme( String tantieme ) {
        this.tantieme = tantieme;
    }
    public String getTantieme() {
        return this.tantieme;
    }

    //--- DATABASE MAPPING : QUOTE_PART ( VARCHAR2 ) 
    public void setQuotePart( String quotePart ) {
        this.quotePart = quotePart;
    }
    public String getQuotePart() {
        return this.quotePart;
    }

    //--- DATABASE MAPPING : DATE_PERMIS_HABITER ( DATE ) 
    public void setDatePermisHabiter( Date datePermisHabiter ) {
        this.datePermisHabiter = datePermisHabiter;
    }
    public Date getDatePermisHabiter() {
        return this.datePermisHabiter;
    }

    //--- DATABASE MAPPING : MNT_TVA ( NUMBER ) 
    public void setMntTva( Long mntTva ) {
        this.mntTva = mntTva;
    }
    public Long getMntTva() {
        return this.mntTva;
    }

    //--- DATABASE MAPPING : ECH_MNT_1 ( NUMBER ) 
    public void setEchMnt1( Long echMnt1 ) {
        this.echMnt1 = echMnt1;
    }
    public Long getEchMnt1() {
        return this.echMnt1;
    }

    //--- DATABASE MAPPING : ECH_MNT_2 ( NUMBER ) 
    public void setEchMnt2( Long echMnt2 ) {
        this.echMnt2 = echMnt2;
    }
    public Long getEchMnt2() {
        return this.echMnt2;
    }

    //--- DATABASE MAPPING : ECH_MNT_3 ( NUMBER ) 
    public void setEchMnt3( Long echMnt3 ) {
        this.echMnt3 = echMnt3;
    }
    public Long getEchMnt3() {
        return this.echMnt3;
    }

    //--- DATABASE MAPPING : ECH_MNT_4 ( NUMBER ) 
    public void setEchMnt4( Long echMnt4 ) {
        this.echMnt4 = echMnt4;
    }
    public Long getEchMnt4() {
        return this.echMnt4;
    }

    //--- DATABASE MAPPING : ECH_DELAI_1 ( NUMBER ) 
    public void setEchDelai1( Long echDelai1 ) {
        this.echDelai1 = echDelai1;
    }
    public Long getEchDelai1() {
        return this.echDelai1;
    }

    //--- DATABASE MAPPING : ECH_DELAI_2 ( NUMBER ) 
    public void setEchDelai2( Long echDelai2 ) {
        this.echDelai2 = echDelai2;
    }
    public Long getEchDelai2() {
        return this.echDelai2;
    }

    //--- DATABASE MAPPING : ECH_DELAI_3 ( NUMBER ) 
    public void setEchDelai3( Long echDelai3 ) {
        this.echDelai3 = echDelai3;
    }
    public Long getEchDelai3() {
        return this.echDelai3;
    }

    //--- DATABASE MAPPING : ECH_DELAI_4 ( NUMBER ) 
    public void setEchDelai4( Long echDelai4 ) {
        this.echDelai4 = echDelai4;
    }
    public Long getEchDelai4() {
        return this.echDelai4;
    }

    //--- DATABASE MAPPING : TYPE_BIEN ( VARCHAR2 ) 
    public void setTypeBien( String typeBien ) {
        this.typeBien = typeBien;
    }
    public String getTypeBien() {
        return this.typeBien;
    }

    //--- DATABASE MAPPING : NIVEAU ( VARCHAR2 ) 
    public void setNiveau( String niveau ) {
        this.niveau = niveau;
    }
    public String getNiveau() {
        return this.niveau;
    }

    //--- DATABASE MAPPING : NUM_BIEN ( VARCHAR2 ) 
    public void setNumBien( String numBien ) {
        this.numBien = numBien;
    }
    public String getNumBien() {
        return this.numBien;
    }

    //--- DATABASE MAPPING : IMMEUBLE ( VARCHAR2 ) 
    public void setImmeuble( String immeuble ) {
        this.immeuble = immeuble;
    }
    public String getImmeuble() {
        return this.immeuble;
    }

    //--- DATABASE MAPPING : ORIENTATION ( VARCHAR2 ) 
    public void setOrientation( String orientation ) {
        this.orientation = orientation;
    }
    public String getOrientation() {
        return this.orientation;
    }

    //--- DATABASE MAPPING : SUP_BALCON ( NUMBER ) 
    public void setSupBalcon( Long supBalcon ) {
        this.supBalcon = supBalcon;
    }
    public Long getSupBalcon() {
        return this.supBalcon;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setReference( ReferenceEntity reference ) {
        this.reference = reference;
    }
    public ReferenceEntity getReference() {
        return this.reference;
    }

    public void setTranche( TrancheEntity tranche ) {
        this.tranche = tranche;
    }
    public TrancheEntity getTranche() {
        return this.tranche;
    }

    public List<TraceDossierEntity> getListOfTraceDossier() {
		return listOfTraceDossier;
	}

	public void setListOfTraceDossier(List<TraceDossierEntity> listOfTraceDossier) {
		this.listOfTraceDossier = listOfTraceDossier;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(denomination);
        sb.append("|");
        sb.append(supProv);
        sb.append("|");
        sb.append(supFinale);
        sb.append("|");
        sb.append(tf);
        sb.append("|");
        sb.append(tfMere);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(prixHt);
        sb.append("|");
        sb.append(prixTtc);
        sb.append("|");
        sb.append(dateLivraison);
        sb.append("|");
        sb.append(ilot);
        sb.append("|");
        sb.append(tantieme);
        sb.append("|");
        sb.append(quotePart);
        sb.append("|");
        sb.append(datePermisHabiter);
        sb.append("|");
        sb.append(mntTva);
        sb.append("|");
        sb.append(echMnt1);
        sb.append("|");
        sb.append(echMnt2);
        sb.append("|");
        sb.append(echMnt3);
        sb.append("|");
        sb.append(echMnt4);
        sb.append("|");
        sb.append(echDelai1);
        sb.append("|");
        sb.append(echDelai2);
        sb.append("|");
        sb.append(echDelai3);
        sb.append("|");
        sb.append(echDelai4);
        sb.append("|");
        sb.append(typeBien);
        sb.append("|");
        sb.append(niveau);
        sb.append("|");
        sb.append(numBien);
        sb.append("|");
        sb.append(immeuble);
        sb.append("|");
        sb.append(orientation);
        sb.append("|");
        sb.append(supBalcon);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
