/*
 * Created on 29 d�c. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;
import java.util.ArrayList;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

import org.codehaus.jackson.annotate.JsonManagedReference;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Persistent class for entity stored in table "CLIENT"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CLIENT", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ClientEntity.countAll", query="SELECT COUNT(x) FROM ClientEntity x" )
} )
public class ClientEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="CILIENT_SEQ", allocationSize=1)
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM_CLIENT", length=200)
    private String     nomClient    ;

    @Column(name="PRENOM_CLIENT", length=200)
    private String     prenomClient ;

    @Column(name="CIN_CLIENT", length=200)
    private String     cinClient    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_EXPIRATION")
    private Date       dateExpiration ;

    @Column(name="ADRESSE", length=200)
    private String     adresse      ;

    @Column(name="REF_PROFESSION")
    private Long       refProfession ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_NAISSANCE")
    private Date       dateNaissance ;

    @Column(name="LIEU_NAISSANCE", length=30)
    private String     lieuNaissance ;

    @Column(name="REF_ETAT_CIVIL")
    private Long       refEtatCivil ;

    @Column(name="TEL_1", length=100)
    private String     tel1         ;

    @Column(name="TEL_2", length=100)
    private String     tel2         ;

    @Column(name="REVENU")
    private Long       revenu       ;

    @Column(name="EMAIL", length=100)
    private String     email        ;

    @Column(name="REF_NATIONALITE")
    private Long       refNationalite ;

    @Column(name="REF_VILLE")
    private Long       refVille     ;

    @Column(name="QUOTE")
    private Long       quote        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="client", targetEntity=DossierClientEntity.class)
    @LazyCollection(LazyCollectionOption.FALSE)
    @JsonManagedReference
    private List<DossierClientEntity> listOfDossierClient = new ArrayList<DossierClientEntity>();


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ClientEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM_CLIENT ( VARCHAR2 ) 
    public void setNomClient( String nomClient ) {
        this.nomClient = nomClient;
    }
    public String getNomClient() {
        return this.nomClient;
    }

    //--- DATABASE MAPPING : PRENOM_CLIENT ( VARCHAR2 ) 
    public void setPrenomClient( String prenomClient ) {
        this.prenomClient = prenomClient;
    }
    public String getPrenomClient() {
        return this.prenomClient;
    }

    //--- DATABASE MAPPING : CIN_CLIENT ( VARCHAR2 ) 
    public void setCinClient( String cinClient ) {
        this.cinClient = cinClient;
    }
    public String getCinClient() {
        return this.cinClient;
    }

    //--- DATABASE MAPPING : DATE_EXPIRATION ( DATE ) 
    public void setDateExpiration( Date dateExpiration ) {
        this.dateExpiration = dateExpiration;
    }
    public Date getDateExpiration() {
        return this.dateExpiration;
    }

    //--- DATABASE MAPPING : ADRESSE ( VARCHAR2 ) 
    public void setAdresse( String adresse ) {
        this.adresse = adresse;
    }
    public String getAdresse() {
        return this.adresse;
    }

    //--- DATABASE MAPPING : REF_PROFESSION ( NUMBER ) 
    public void setRefProfession( Long refProfession ) {
        this.refProfession = refProfession;
    }
    public Long getRefProfession() {
        return this.refProfession;
    }

    //--- DATABASE MAPPING : DATE_NAISSANCE ( DATE ) 
    public void setDateNaissance( Date dateNaissance ) {
        this.dateNaissance = dateNaissance;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }

    //--- DATABASE MAPPING : LIEU_NAISSANCE ( VARCHAR2 ) 
    public void setLieuNaissance( String lieuNaissance ) {
        this.lieuNaissance = lieuNaissance;
    }
    public String getLieuNaissance() {
        return this.lieuNaissance;
    }

    //--- DATABASE MAPPING : REF_ETAT_CIVIL ( NUMBER ) 
    public void setRefEtatCivil( Long refEtatCivil ) {
        this.refEtatCivil = refEtatCivil;
    }
    public Long getRefEtatCivil() {
        return this.refEtatCivil;
    }

    //--- DATABASE MAPPING : TEL_1 ( VARCHAR2 ) 
    public void setTel1( String tel1 ) {
        this.tel1 = tel1;
    }
    public String getTel1() {
        return this.tel1;
    }

    //--- DATABASE MAPPING : TEL_2 ( VARCHAR2 ) 
    public void setTel2( String tel2 ) {
        this.tel2 = tel2;
    }
    public String getTel2() {
        return this.tel2;
    }

    //--- DATABASE MAPPING : REVENU ( NUMBER ) 
    public void setRevenu( Long revenu ) {
        this.revenu = revenu;
    }
    public Long getRevenu() {
        return this.revenu;
    }

    //--- DATABASE MAPPING : EMAIL ( VARCHAR2 ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : REF_NATIONALITE ( NUMBER ) 
    public void setRefNationalite( Long refNationalite ) {
        this.refNationalite = refNationalite;
    }
    public Long getRefNationalite() {
        return this.refNationalite;
    }

    //--- DATABASE MAPPING : REF_VILLE ( NUMBER ) 
    public void setRefVille( Long refVille ) {
        this.refVille = refVille;
    }
    public Long getRefVille() {
        return this.refVille;
    }

    //--- DATABASE MAPPING : QUOTE ( NUMBER ) 
    public void setQuote( Long quote ) {
        this.quote = quote;
    }
    public Long getQuote() {
        return this.quote;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfDossierClient( List<DossierClientEntity> listOfDossierClient ) {
        this.listOfDossierClient = listOfDossierClient;
    }
    
    public List<DossierClientEntity> getListOfDossierClient() {
        return this.listOfDossierClient;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nomClient);
        sb.append("|");
        sb.append(prenomClient);
        sb.append("|");
        sb.append(cinClient);
        sb.append("|");
        sb.append(dateExpiration);
        sb.append("|");
        sb.append(adresse);
        sb.append("|");
        sb.append(refProfession);
        sb.append("|");
        sb.append(dateNaissance);
        sb.append("|");
        sb.append(lieuNaissance);
        sb.append("|");
        sb.append(refEtatCivil);
        sb.append("|");
        sb.append(tel1);
        sb.append("|");
        sb.append(tel2);
        sb.append("|");
        sb.append(revenu);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(refNationalite);
        sb.append("|");
        sb.append(refVille);
        sb.append("|");
        sb.append(quote);
        return sb.toString(); 
    } 

}
