/*
 * Created on 29 d�c. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "DOSSIER"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="DOSSIER", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DossierEntity.countAll", query="SELECT COUNT(x) FROM DossierEntity x" )
} )
public class DossierEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="DOSSIER_SEQ", allocationSize=1)
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="REF_BIEN")
    private Long       refBien      ;

    @Column(name="COMMERCIAL", length=100)
    private String     commercial   ;

    @Column(name="ETAT", length=100)
    private String     etat         ;

    @Column(name="REF_PROJET")
    private Long       refProjet    ;

    @Column(name="REF_TRANCHE")
    private Long       refTranche   ;

    @Column(name="TYPE_DESISTEMENT")
    private Long       typeDesistement ;

    @Column(name="DATE_DESISTEMENT")
    private Long       dateDesistement ;

    @Column(name="NUM_DOSS_DOC", length=100)
    private String     numDossDoc   ;

    @Column(name="REF_CONVENTION")
    private Long       refConvention ;

    @Column(name="NUM_VENTE_PROJET")
    private Long       numVenteProjet ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FACTURATION")
    private Date       dateFacturation      ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="dossier", targetEntity=RecetteEntity.class)
    private List<RecetteEntity> listOfRecette;

    @OneToMany(mappedBy="dossier", targetEntity=DossierClientEntity.class)
    private List<DossierClientEntity> listOfDossierClient;

    @OneToMany(mappedBy="dossier", targetEntity=EcheanceEntity.class)
    private List<EcheanceEntity> listOfEcheance;

    @OneToMany(mappedBy="dossier", targetEntity=TraceDossierEntity.class)
    private List<TraceDossierEntity> listOfTraceDossier;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DossierEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : REF_BIEN ( NUMBER ) 
    public void setRefBien( Long refBien ) {
        this.refBien = refBien;
    }
    public Long getRefBien() {
        return this.refBien;
    }

    //--- DATABASE MAPPING : COMMERCIAL ( VARCHAR2 ) 
    public void setCommercial( String commercial ) {
        this.commercial = commercial;
    }
    public String getCommercial() {
        return this.commercial;
    }

    //--- DATABASE MAPPING : ETAT ( VARCHAR2 ) 
    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    //--- DATABASE MAPPING : REF_PROJET ( NUMBER ) 
    public void setRefProjet( Long refProjet ) {
        this.refProjet = refProjet;
    }
    public Long getRefProjet() {
        return this.refProjet;
    }

    //--- DATABASE MAPPING : REF_TRANCHE ( NUMBER ) 
    public void setRefTranche( Long refTranche ) {
        this.refTranche = refTranche;
    }
    public Long getRefTranche() {
        return this.refTranche;
    }

    //--- DATABASE MAPPING : TYPE_DESISTEMENT ( NUMBER ) 
    public void setTypeDesistement( Long typeDesistement ) {
        this.typeDesistement = typeDesistement;
    }
    public Long getTypeDesistement() {
        return this.typeDesistement;
    }

    //--- DATABASE MAPPING : DATE_DESISTEMENT ( NUMBER ) 
    public void setDateDesistement( Long dateDesistement ) {
        this.dateDesistement = dateDesistement;
    }
    public Long getDateDesistement() {
        return this.dateDesistement;
    }

    //--- DATABASE MAPPING : NUM_DOSS_DOC ( VARCHAR2 ) 
    public void setNumDossDoc( String numDossDoc ) {
        this.numDossDoc = numDossDoc;
    }
    public String getNumDossDoc() {
        return this.numDossDoc;
    }

    //--- DATABASE MAPPING : REF_CONVENTION ( NUMBER ) 
    public void setRefConvention( Long refConvention ) {
        this.refConvention = refConvention;
    }
    public Long getRefConvention() {
        return this.refConvention;
    }

    //--- DATABASE MAPPING : NUM_VENTE_PROJET ( NUMBER ) 
    public void setNumVenteProjet( Long numVenteProjet ) {
        this.numVenteProjet = numVenteProjet;
    }
    public Long getNumVenteProjet() {
        return this.numVenteProjet;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

  //--- DATABASE MAPPING : DATE_FACTURATION ( DATE ) 
    public Date getDateFacturation() {
		return dateFacturation;
	}

	public void setDateFacturation(Date dateFacturation) {
		this.dateFacturation = dateFacturation;
	}

	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfRecette( List<RecetteEntity> listOfRecette ) {
        this.listOfRecette = listOfRecette;
    }
    public List<RecetteEntity> getListOfRecette() {
        return this.listOfRecette;
    }

    public void setListOfDossierClient( List<DossierClientEntity> listOfDossierClient ) {
        this.listOfDossierClient = listOfDossierClient;
    }
    public List<DossierClientEntity> getListOfDossierClient() {
        return this.listOfDossierClient;
    }

    public void setListOfEcheance( List<EcheanceEntity> listOfEcheance ) {
        this.listOfEcheance = listOfEcheance;
    }
    public List<EcheanceEntity> getListOfEcheance() {
        return this.listOfEcheance;
    }

    public List<TraceDossierEntity> getListOfTraceDossier() {
		return listOfTraceDossier;
	}

	public void setListOfTraceDossier(List<TraceDossierEntity> listOfTraceDossier) {
		this.listOfTraceDossier = listOfTraceDossier;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(refBien);
        sb.append("|");
        sb.append(commercial);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(refProjet);
        sb.append("|");
        sb.append(refTranche);
        sb.append("|");
        sb.append(typeDesistement);
        sb.append("|");
        sb.append(dateDesistement);
        sb.append("|");
        sb.append(numDossDoc);
        sb.append("|");
        sb.append(refConvention);
        sb.append("|");
        sb.append(numVenteProjet);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
