/*
 * Created on 29 déc. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "MODULE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="MODULE", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ModuleEntity.countAll", query="SELECT COUNT(x) FROM ModuleEntity x" )
} )
public class ModuleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NIVEAU", length=100)
    private String     niveau       ;

    @Column(name="ID_CONPONENET", length=100)
    private String     idConponenet ;

    @Column(name="DOMAINE", length=100)
    private String     domaine      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="module", targetEntity=ModuleProfilEntity.class)
    private List<ModuleProfilEntity> listOfModuleProfil;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ModuleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NIVEAU ( VARCHAR2 ) 
    public void setNiveau( String niveau ) {
        this.niveau = niveau;
    }
    public String getNiveau() {
        return this.niveau;
    }

    //--- DATABASE MAPPING : ID_CONPONENET ( VARCHAR2 ) 
    public void setIdConponenet( String idConponenet ) {
        this.idConponenet = idConponenet;
    }
    public String getIdConponenet() {
        return this.idConponenet;
    }

    //--- DATABASE MAPPING : DOMAINE ( VARCHAR2 ) 
    public void setDomaine( String domaine ) {
        this.domaine = domaine;
    }
    public String getDomaine() {
        return this.domaine;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfModuleProfil( List<ModuleProfilEntity> listOfModuleProfil ) {
        this.listOfModuleProfil = listOfModuleProfil;
    }
    public List<ModuleProfilEntity> getListOfModuleProfil() {
        return this.listOfModuleProfil;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(niveau);
        sb.append("|");
        sb.append(idConponenet);
        sb.append("|");
        sb.append(domaine);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
