/*
 * Created on 29 d�c. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "RECETTE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RECETTE", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RecetteEntity.countAll", query="SELECT COUNT(x) FROM RecetteEntity x" )
} )
public class RecetteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="RECETTE_SEQ", allocationSize=1)
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="BANQUE", length=30)
    private String     banque       ;

    @Column(name="MONTANT")
    private Long       montant      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DEPOT")
    private Date       dateDepot    ;

    @Column(name="REF_VILLE")
    private Long       refVille     ;

    @Column(name="NOM_PAYEUR", length=100)
    private String     nomPayeur    ;

    @Column(name="NUM_RECETTE", length=100)
    private String     numRecette   ;

    @Column(name="REF_MODE_RECETTE")
    private Long       refModeRecette ;

    @Column(name="ETAT", length=10)
    private String     etat         ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

    @Column(name="REF_ECHEANCE")
    private Long       refEcheance  ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="DATE_VERSEMENT")
    private Date       dateVersement ;

	// "refDossier" (column "REF_DOSSIER") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="REF_DOSSIER", referencedColumnName="ID")
    private DossierEntity dossier     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RecetteEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : BANQUE ( VARCHAR2 ) 
    public void setBanque( String banque ) {
        this.banque = banque;
    }
    public String getBanque() {
        return this.banque;
    }

    //--- DATABASE MAPPING : MONTANT ( NUMBER ) 
    public void setMontant( Long montant ) {
        this.montant = montant;
    }
    public Long getMontant() {
        return this.montant;
    }

    //--- DATABASE MAPPING : DATE_DEPOT ( DATE ) 
    public void setDateDepot( Date dateDepot ) {
        this.dateDepot = dateDepot;
    }
    public Date getDateDepot() {
        return this.dateDepot;
    }

    //--- DATABASE MAPPING : REF_VILLE ( NUMBER ) 
    public void setRefVille( Long refVille ) {
        this.refVille = refVille;
    }
    public Long getRefVille() {
        return this.refVille;
    }

    //--- DATABASE MAPPING : NOM_PAYEUR ( VARCHAR2 ) 
    public void setNomPayeur( String nomPayeur ) {
        this.nomPayeur = nomPayeur;
    }
    public String getNomPayeur() {
        return this.nomPayeur;
    }

    //--- DATABASE MAPPING : NUM_RECETTE ( VARCHAR2 ) 
    public void setNumRecette( String numRecette ) {
        this.numRecette = numRecette;
    }
    public String getNumRecette() {
        return this.numRecette;
    }

    //--- DATABASE MAPPING : REF_MODE_RECETTE ( NUMBER ) 
    public void setRefModeRecette( Long refModeRecette ) {
        this.refModeRecette = refModeRecette;
    }
    public Long getRefModeRecette() {
        return this.refModeRecette;
    }

    //--- DATABASE MAPPING : ETAT ( VARCHAR2 ) 
    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    //--- DATABASE MAPPING : REF_ECHEANCE ( NUMBER ) 
    public void setRefEcheance( Long refEcheance ) {
        this.refEcheance = refEcheance;
    }
    public Long getRefEcheance() {
        return this.refEcheance;
    }
    
    //--- DATABASE MAPPING : DATE_VERSEMENT ( DATE )
    public Date getDateVersement() {
		return dateVersement;
	}

	public void setDateVersement(Date dateVersement) {
		this.dateVersement = dateVersement;
	}

	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDossier( DossierEntity dossier ) {
        this.dossier = dossier;
    }
    public DossierEntity getDossier() {
        return this.dossier;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(banque);
        sb.append("|");
        sb.append(montant);
        sb.append("|");
        sb.append(dateDepot);
        sb.append("|");
        sb.append(refVille);
        sb.append("|");
        sb.append(nomPayeur);
        sb.append("|");
        sb.append(numRecette);
        sb.append("|");
        sb.append(refModeRecette);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(refEcheance);
        return sb.toString(); 
    } 

}
