/*
 * Created on 29 déc. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "REFERENCE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="REFERENCE", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ReferenceEntity.countAll", query="SELECT COUNT(x) FROM ReferenceEntity x" )
} )
public class ReferenceEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="LIBELLE", length=100)
    private String     libelle      ;

    @Column(name="ORDRE")
    private Long       ordre        ;

    @Column(name="REF_PROJET")
    private Long       refProjet    ;

	// "refTypeReference" (column "REF_TYPE_REFERENCE") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="reference", targetEntity=BienEntity.class)
    private List<BienEntity> listOfBien  ;

    @ManyToOne
    @JoinColumn(name="REF_TYPE_REFERENCE", referencedColumnName="ID")
    private ReferenceTypeEntity referenceType;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ReferenceEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : LIBELLE ( VARCHAR2 ) 
    public void setLibelle( String libelle ) {
        this.libelle = libelle;
    }
    public String getLibelle() {
        return this.libelle;
    }

    //--- DATABASE MAPPING : ORDRE ( NUMBER ) 
    public void setOrdre( Long ordre ) {
        this.ordre = ordre;
    }
    public Long getOrdre() {
        return this.ordre;
    }

    //--- DATABASE MAPPING : REF_PROJET ( NUMBER ) 
    public void setRefProjet( Long refProjet ) {
        this.refProjet = refProjet;
    }
    public Long getRefProjet() {
        return this.refProjet;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfBien( List<BienEntity> listOfBien ) {
        this.listOfBien = listOfBien;
    }
    public List<BienEntity> getListOfBien() {
        return this.listOfBien;
    }

    public void setReferenceType( ReferenceTypeEntity referenceType ) {
        this.referenceType = referenceType;
    }
    public ReferenceTypeEntity getReferenceType() {
        return this.referenceType;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(libelle);
        sb.append("|");
        sb.append(ordre);
        sb.append("|");
        sb.append(refProjet);
        return sb.toString(); 
    } 

}
