/*
 * Created on 29 d�c. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "TRANCHE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="TRANCHE", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TrancheEntity.countAll", query="SELECT COUNT(x) FROM TrancheEntity x" )
} )
public class TrancheEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="TRANCHE_SEQ", allocationSize=1)
    @Column(name="ID", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="LIBELLE", length=100)
    private String     libelle      ;

    @Column(name="DESCRIPTION", length=200)
    private String     description  ;

    @Column(name="TYPE_TRANCHE", length=100)
    private String     typeTranche  ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

	// "refProjet" (column "REF_PROJET") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="tranche", targetEntity=UtilisateurTrancheEntity.class)
    private List<UtilisateurTrancheEntity> listOfUtilisateurTranche;

    @OneToMany(mappedBy="tranche", targetEntity=BienEntity.class)
    private List<BienEntity> listOfBien  ;

    @ManyToOne
    @JoinColumn(name="REF_PROJET", referencedColumnName="ID")
    private ProjetEntity projet      ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TrancheEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : LIBELLE ( VARCHAR2 ) 
    public void setLibelle( String libelle ) {
        this.libelle = libelle;
    }
    public String getLibelle() {
        return this.libelle;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( VARCHAR2 ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : TYPE_TRANCHE ( VARCHAR2 ) 
    public void setTypeTranche( String typeTranche ) {
        this.typeTranche = typeTranche;
    }
    public String getTypeTranche() {
        return this.typeTranche;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUtilisateurTranche( List<UtilisateurTrancheEntity> listOfUtilisateurTranche ) {
        this.listOfUtilisateurTranche = listOfUtilisateurTranche;
    }
    public List<UtilisateurTrancheEntity> getListOfUtilisateurTranche() {
        return this.listOfUtilisateurTranche;
    }

    public void setListOfBien( List<BienEntity> listOfBien ) {
        this.listOfBien = listOfBien;
    }
    public List<BienEntity> getListOfBien() {
        return this.listOfBien;
    }

    public void setProjet( ProjetEntity projet ) {
        this.projet = projet;
    }
    public ProjetEntity getProjet() {
        return this.projet;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(libelle);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(typeTranche);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
