/*
 * Created on 29 d�c. 2015 ( Time 20:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.immo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "UTILISATEUR"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="UTILISATEUR", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UtilisateurEntity.countAll", query="SELECT COUNT(x) FROM UtilisateurEntity x" )
} )
public class UtilisateurEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    @GeneratedValue(generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="SEQ_UTILISATEUR", allocationSize=1)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", length=100)
    private String     nom          ;

    @Column(name="PRENOM", length=100)
    private String     prenom       ;

    @Column(name="LOGIN", length=100)
    private String     login        ;

    @Column(name="PASSWORD", length=100)
    private String     password     ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

	// "refProfil" (column "REF_PROFIL") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="REF_PROFIL", referencedColumnName="ID")
    private ProfilEntity profil      ;

    @OneToMany(mappedBy="utilisateur", targetEntity=UtilisateurTrancheEntity.class)
    private List<UtilisateurTrancheEntity> listOfUtilisateurTranche;

    @OneToMany(mappedBy="utilisateur", targetEntity=TraceDossierEntity.class)
    private List<TraceDossierEntity> listOfTraceDossier;
    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UtilisateurEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR2 ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRENOM ( VARCHAR2 ) 
    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }
    public String getPrenom() {
        return this.prenom;
    }

    //--- DATABASE MAPPING : LOGIN ( VARCHAR2 ) 
    public void setLogin( String login ) {
        this.login = login;
    }
    public String getLogin() {
        return this.login;
    }

    //--- DATABASE MAPPING : PASSWORD ( VARCHAR2 ) 
    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProfil( ProfilEntity profil ) {
        this.profil = profil;
    }
    public ProfilEntity getProfil() {
        return this.profil;
    }

    public void setListOfUtilisateurTranche( List<UtilisateurTrancheEntity> listOfUtilisateurTranche ) {
        this.listOfUtilisateurTranche = listOfUtilisateurTranche;
    }
    public List<UtilisateurTrancheEntity> getListOfUtilisateurTranche() {
        return this.listOfUtilisateurTranche;
    }

    public List<TraceDossierEntity> getListOfTraceDossier() {
		return listOfTraceDossier;
	}
	public void setListOfTraceDossier(List<TraceDossierEntity> listOfTraceDossier) {
		this.listOfTraceDossier = listOfTraceDossier;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(prenom);
        sb.append("|");
        sb.append(login);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
